graviton_rest_routing:
    resource: "@GravitonRestBundle/Resources/config/routing.xml"
    prefix: /

graviton_core_routing:
    resource: "@GravitonCoreBundle/Resources/config/routing.xml"
    prefix: /

graviton_swagger_routing:
    resource: "@GravitonSwaggerBundle/Resources/config/routing.xml"
    prefix: /

graviton_proxy_routing:
    resource: "@GravitonProxyBundle/Resources/config/routing.xml"
    prefix: /

graviton_security_routing:
    resource: "@GravitonSecurityBundle/Resources/config/routing.xml"
    prefix: /

#app:
    #resource: "@AppBundle/Controller/"
    #type:     annotation
